#all: getFeatures get_SAT_UNSAT_examples

#getFeatures: getFeatures.cc
#	g++ -o getFeatures.out getFeatures.cc -I/usr/include/coin -L/usr/lib/x86_64-linux-gnu/ -lClp -lCoinUtils  -std=c++11

get_SAT_UNSAT_examples: get_SAT_UNSAT_examples.cc
        g++ -o get_SAT_UNSAT_examples.out -std=c++11 get_SAT_UNSAT_examples.cc

g++ -o createMinu1.out -std=c++11 createMinu1.cc

g++ -o predictBackbone.out -std=c++11 predictBackbone.cc
